service: pruebaFinaktiva

frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  memorySize: 128
  region: us-east-1

configValidationMode: error

functions:
  app1:
    name: api-express
    description: api to pruebaFinaktiva
    handler: index.handler
    events:
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY
